#!/bin/sh

N=$1
NMINUS1=$(( $N - 1))

for i in $(seq $NMINUS1); do
    f="file-$i"
    if [ ! -e $f ] ; then
       echo "ERROR: can't find $f"
       exit 1
    fi
    cat $f > file-$N.tmp
done

echo "$N: $(date)" >> file-$N.tmp

mv -f file-$N.tmp file-$N
