name: test

on:
  push:

jobs:
  build1:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Touch 1
      run: |
        ./touch 1

    - name: Archive artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-${{ runner.os }}-${{ runner.arch }}-${{ github.run_id }}
        path: |
          output/

  build2:
    needs: build1
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: actions/download-artifact@v3
      with:
        name: build-${{ runner.os }}-${{ runner.arch }}-${{ github.run_id }}

    - name: Find
      run: |
        find /home/runner/work/gha-test/gha-test
        find .
    - name: Touch 2
      run: ./touch 2

    - name: Touch 3
      run: ./touch 3


