name: Testing Github Actions

on:
  push:

jobs:
  build1:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Touch 1
      run: ./touch 1

    - name: Cache Write
      uses: actions/cache@v3
      with:
        path: file-1
        key: test-${{ github.run_id }}
        restore-keys: test-

  build2:
    needs: [build1]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Cache Read
      uses: actions/cache@v3
      with:
        path: file-1
        key: test-${{ github.run_id }}

    - name: Touch 2
      run: ./touch 2

  build2a:
    needs: [build1]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Touch 2
      run: ./touch 2


  build3:
    needs: [build2]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Touch 3
      run: ./touch 3
