name: test

on:
  push:

jobs:
  builds:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Touch 1
      if: github.ref_name != 'test'
      run: |
        ./touch 1
        mkdir -p output/foo/baa

    - name: Archive artifacts
      if: github.ref_name != 'test'
      uses: actions/upload-artifact@v3
      with:
        name: build-1
        path: |
          output/

    - name: Get artifacts
      if: github.ref_name == 'test'
      continue-on-error: true
      uses: dawidd6/action-download-artifact@v2
      with:
        branch: main

    - name: Move build-1
      if: github.ref_name == 'test'
      run: mv build-1/* .

    - name: Touch 2
      run: ./touch 2

    - name: Touch 3
      run: ./touch 3
