name: test

on:
  push:

jobs:
  builds:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Touch 1
      if: github.ref_name != 'test'
      run: ./touch 1

    - name: Archive artifacts
      if: github.ref_name != 'test'
      uses: actions/upload-artifact@v3
      with:
        name: build-1
        path: |
          file-1

    - name: Get build-1
      if: github.ref_name == 'test'
      continue-on-error: true
      uses: dawidd6/action-download-artifact@v2
      with:
        branch: main

    - name: Touch 2
      run: ./touch 2

    - name: Touch 3
      run: ./touch 3
