name: 'test'

on:
  push:
  pull_request:

jobs:
  build1:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: ./touch 1
    with:
    - uses: actions/cache@v3
    - path: file-1
    - key: test-${{ github.run_id }}
    - restore-keys: test-

  build2:
    needs: [build1]
    runs-on: ubuntu-latest
    with:
    - uses: actions/cache@v3
    - path: file-1
    - key: test-${{ github.run_id }}
    steps:
    - uses: actions/checkout@v3
    - run: ./touch 2
