name: test

on:
  push:

jobs:
  build1:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Touch 1
      run: |
        ./touch 1

    - name: Archive artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-${{ runner.os }}-${{ runner.arch }}-${{ github.run_id }}
        path: |
          output/

  build2:
    needs: build1
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: actions/download-artifact@v3
      with:
        name: build-${{ runner.os }}-${{ runner.arch }}-${{ github.run_id }}
    - name: Move
      run: |
        mkdir -p output
        mv file-1 output
    - name: Touch 2
      run: ./touch 2

    - name: Touch 3
      run: ./touch 3


