name: test

on:
  push:

jobs:
  build1:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Touch 1
      run: |
        ./touch 1

    - name: Archive artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-${{ runner.os }}-${{ runner.arch }}
        path: |
          output/file-1

  build2:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: dawidd6/action-download-artifact@v2
      with:
        name: build-${{ runner.os }}-${{ runner.arch }}

    - name: Touch 2
      run: ./touch 2

    - name: Touch 3
      run: ./touch 3
